### ISSUE TITLE
when i run the first exaple FRC Based RL deconvolution.ipynb, i got the error:,what happened?

### ISSUE THREAD

**Issue by Amarintine** [sakoho81/miplib#1]
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    image = imread.get_image(full_path, channel=0)
  File "/home/luvis/chenxu/miplib-public/miplib/data/io/read.py", line 30, in get_image
    data = __bioformats(filename, series, channel, return_type == 'itk')
  File "/home/luvis/chenxu/miplib-public/miplib/data/io/read.py", line 156, in __bioformats
    image = pims.bioformats.BioformatsReader(filename, series=series)
  File "/home/luvis/anaconda3/envs/miplib/lib/python3.6/site-packages/pims/bioformats.py", line 334, in __init__
    log4j.BasicConfigurator.configure()
  File "/home/luvis/anaconda3/envs/miplib/lib/python3.6/site-packages/jpype/_jpackage.py", line 62, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package org.apache.log4j.BasicConfigurator.configure is not Callable

**Comment by sakoho81** [comment]
Hi,

I haven't seen that error before, but you seem to have some sort of a problem with permissions or Java runtime in your system. The Java is needed for the Bioformats reader. Like you see, the code tries to load  *org.apache.log4j.BasicConfigurator.configure* package, but reports that it *is not Callable*. Maybe try checking that you have Java runtime installed.
